config/routes.rb
ExpressoServer::Application.routes.draw do
  resources :categories

  match 'usuari/edit' => 'usuaris#edit', :as => :edit_current_usuari

  root :to => 'begudes#index'

  match 'login' => 'sessions#new', :as => :login

  match 'signup' => 'usuaris#new', :as => :signup

  match 'logout' => 'sessions#destroy', :as => :logout

  resources :sessions

  resources :extra_disponibles

  resources :topings

  resources :extres

  resources :begudes

  resources :comandes

  resources :usuaris

  resources :botigues
  
  match 'api/login' => 'api#login'
  match 'api/carta' => 'api#carta'

end

app/models/beguda.rb
class Beguda < ActiveRecord::Base
  has_many :extresDisponibles, dependent: :destroy
  has_many :extres, through: :extresDisponibles
  
  def afegirExtres(llistaExtres)
    self.extres.clear
    if (llistaExtres != nil) 
      llistaExtres.each do |extra|
        extraObj = Extra.find(extra)
        self.extres << extraObj
      end
    end
  end
end

app/models/botiga.rb
class Botiga < ActiveRecord::Base
  has_many :comandes
end

app/models/categoria.rb
class Categoria < ActiveRecord::Base
  has_many :begudes
end

app/models/comanda.rb
class Comanda < ActiveRecord::Base
  has_many :topings, dependent: :destroy
  has_many :extres, through: :topings
  
  has_one :beguda
end

app/models/extra.rb
class Extra < ActiveRecord::Base
end

app/models/extra_disponible.rb
class ExtraDisponible < ActiveRecord::Base
  belongs_to :beguda
  belongs_to :extra
end

app/models/remot.rb
class Remot < ActiveRecord::Base
  belongs_to :usuari
  
  App_halt = "$2a$10$dRwXuvlT8j6yPYBQYgNke."

  def create
    self.hash = BCrypt::Engine.hash_secret(Time.now.to_s, App_halt)
    super
  end
end

app/models/toping.rb
class Toping < ActiveRecord::Base
  belongs_to :comanda
  belongs_to :extra
end

app/models/usuari.rb
class Usuari < ActiveRecord::Base
  # new columns need to be added here to be writable through mass assignment
  has_many :comandes
  has_one :remot
  attr_accessible :username, :email, :password, :password_confirmation, :saldo

  attr_accessor :password
  before_save :prepare_password

  validates_presence_of :username
  validates_uniqueness_of :username, :email, :allow_blank => true
  validates_format_of :username, :with => /^[-\w\._@]+$/i, :allow_blank => true, :message => "should only contain letters, numbers, or .-_@"
  validates_format_of :email, :with => /^[-a-z0-9_+\.]+\@([-a-z0-9]+\.)+[a-z0-9]{2,4}$/i
  validates_presence_of :password , only: [:create,:update]
  validates_confirmation_of :password 
  validates_length_of :password, :minimum => 4, :allow_blank => true

  # login can be either username or email address
  def self.authenticate(login, pass)
    usuari = self.find(:first, :conditions => [ "lower(username) = ?",login.downcase ]) || find_by_email(login)
    return usuari if usuari && usuari.password_hash == usuari.encrypt_password(pass)
  end

  def encrypt_password(pass)
    BCrypt::Engine.hash_secret(pass, password_salt)
  end

  private

  def prepare_password
    unless password.blank?
      self.password_salt = BCrypt::Engine.generate_salt
      self.password_hash = encrypt_password(password)
    end
  end
end

app/controllers/api_controller.rb
class ApiController < ApplicationController
  skip_before_filter :login_required
  
  def login
    usuari = Usuari.authenticate(params[:user], params[:pass])
    

    json=""
    if usuari
      result = 1
      credits = usuari.saldo
      
      remot = usuari.create_remot
      
      json = "{\"result\":#{result}, \"credits\":#{credits}, \"idSessio\":\"#{remot.hash}\"}"
    else
      result = 0
      
      json = "{\"result\":#{result}}"
    end
    
    render json: json
  end
  
  def carta
    categories = Categoria.includes(:begudes).find(:all)
    render json: categories.to_json(include: { begudes: { include: :extres }}, except: [:created_at, :updated_at])
  end
end

app/controllers/comandes_controller.rb
class ComandesController < ApplicationController
  # GET /comandes
  # GET /comandes.json
  def index
    @comandes = Comanda.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @comandes }
    end
  end

  # GET /comandes/1
  # GET /comandes/1.json
  def show
    @comanda = Comanda.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @comanda }
    end
  end

  # GET /comandes/new
  # GET /comandes/new.json
  def new
    @comanda = Comanda.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @comanda }
    end
  end

  # GET /comandes/1/edit
  def edit
    @comanda = Comanda.find(params[:id])
  end

  # POST /comandes
  # POST /comandes.json
  def create
    @comanda = Comanda.new(params[:comanda])

    respond_to do |format|
      if @comanda.save
        format.html { redirect_to @comanda, notice: 'Comanda was successfully created.' }
        format.json { render json: @comanda, status: :created, location: @comanda }
      else
        format.html { render action: "new" }
        format.json { render json: @comanda.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /comandes/1
  # PUT /comandes/1.json
  def update
    @comanda = Comanda.find(params[:id])

    respond_to do |format|
      if @comanda.update_attributes(params[:comanda])
        format.html { redirect_to @comanda, notice: 'Comanda was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render action: "edit" }
        format.json { render json: @comanda.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /comandes/1
  # DELETE /comandes/1.json
  def destroy
    @comanda = Comanda.find(params[:id])
    @comanda.destroy

    respond_to do |format|
      format.html { redirect_to comandes_url }
      format.json { head :ok }
    end
  end
end

app/helpers/api_helper.rb
module ApiHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/begudes_helper.rb
module BegudesHelper
end

app/helpers/botigues_helper.rb
module BotiguesHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/comandes_helper.rb
module ComandesHelper
end

app/helpers/extres_helper.rb
module ExtresHelper
end

app/helpers/layout_helper.rb
# These helper methods can be called in your template to set variables to be used in the layout
# This module should be included in all views globally,
# to do so you may need to add this line to your ApplicationController
#   helper :layout
module LayoutHelper
  def title(page_title, show_title = true)
    content_for(:title) { h(page_title.to_s) }
    @show_title = show_title
  end

  def show_title?
    @show_title
  end

  def stylesheet(*args)
    content_for(:head) { stylesheet_link_tag(*args) }
  end

  def javascript(*args)
    content_for(:head) { javascript_include_tag(*args) }
  end
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/topings_helper.rb
module TopingsHelper
end

app/helpers/usuaris_helper.rb
module UsuarisHelper
end

app/views/comandes/_form.html.erb
<%= form_for(@comanda) do |f| %>
  <% if @comanda.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@comanda.errors.count, "error") %> prohibited this comanda from being saved:</h2>

      <ul>
      <% @comanda.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :usuari_id %><br />
    <%= f.number_field :usuari_id %>
  </div>
  <div class="field">
    <%= f.label :beguda_id %><br />
    <%= f.text_field :beguda_id %>
  </div>
  <div class="field">
    <%= f.label :feta %><br />
    <%= f.check_box :feta %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/comandes/edit.html.erb
<h1>Editing comanda</h1>

<%= render 'form' %>

<%= link_to 'Show', @comanda %> |
<%= link_to 'Back', comandes_path %>

app/views/comandes/index.html.erb
<h1>Listing comandes</h1>

<table>
  <tr>
    <th>Usuari</th>
    <th>Beguda</th>
    <th>Feta</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @comandes.each do |comanda| %>
  <tr>
    <td><%= comanda.usuari_id %></td>
    <td><%= comanda.beguda_id %></td>
    <td><%= comanda.feta %></td>
    <td><%= link_to 'Show', comanda %></td>
    <td><%= link_to 'Edit', edit_comanda_path(comanda) %></td>
    <td><%= link_to 'Destroy', comanda, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Comanda', new_comanda_path %>

app/views/comandes/new.html.erb
<h1>New comanda</h1>

<%= render 'form' %>

<%= link_to 'Back', comandes_path %>

app/views/comandes/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Usuari:</b>
  <%= @comanda.usuari_id %>
</p>

<p>
  <b>Beguda:</b>
  <%= @comanda.beguda_id %>
</p>

<p>
  <b>Feta:</b>
  <%= @comanda.feta %>
</p>


<%= link_to 'Edit', edit_comanda_path(@comanda) %> |
<%= link_to 'Back', comandes_path %>