config/routes.rb
ExpressoServer::Application.routes.draw do
  resources :categories

  match 'usuari/edit' => 'usuaris#edit', :as => :edit_current_usuari

  root :to => 'begudes#index'

  match 'login' => 'sessions#new', :as => :login

  match 'signup' => 'usuaris#new', :as => :signup

  match 'logout' => 'sessions#destroy', :as => :logout

  resources :sessions

  resources :extra_disponibles

  resources :topings

  resources :extres

  resources :begudes

  resources :comandes

  resources :usuaris

  resources :botigues
  
  match 'api/login' => 'api#login'
  match 'api/carta' => 'api#carta'

end

app/models/beguda.rb
class Beguda < ActiveRecord::Base
  has_many :extresDisponibles, dependent: :destroy
  has_many :extres, through: :extresDisponibles
  
  def afegirExtres(llistaExtres)
    self.extres.clear
    if (llistaExtres != nil) 
      llistaExtres.each do |extra|
        extraObj = Extra.find(extra)
        self.extres << extraObj
      end
    end
  end
end

app/models/botiga.rb
class Botiga < ActiveRecord::Base
  has_many :comandes
end

app/models/categoria.rb
class Categoria < ActiveRecord::Base
  has_many :begudes
end

app/models/comanda.rb
class Comanda < ActiveRecord::Base
  has_many :topings, dependent: :destroy
  has_many :extres, through: :topings
  
  has_one :beguda
end

app/models/extra.rb
class Extra < ActiveRecord::Base
end

app/models/extra_disponible.rb
class ExtraDisponible < ActiveRecord::Base
  belongs_to :beguda
  belongs_to :extra
end

app/models/remot.rb
class Remot < ActiveRecord::Base
  belongs_to :usuari
  
  App_halt = "$2a$10$dRwXuvlT8j6yPYBQYgNke."

  def create
    self.hash = BCrypt::Engine.hash_secret(Time.now.to_s, App_halt)
    super
  end
end

app/models/toping.rb
class Toping < ActiveRecord::Base
  belongs_to :comanda
  belongs_to :extra
end

app/models/usuari.rb
class Usuari < ActiveRecord::Base
  # new columns need to be added here to be writable through mass assignment
  has_many :comandes
  has_one :remot
  attr_accessible :username, :email, :password, :password_confirmation, :saldo

  attr_accessor :password
  before_save :prepare_password

  validates_presence_of :username
  validates_uniqueness_of :username, :email, :allow_blank => true
  validates_format_of :username, :with => /^[-\w\._@]+$/i, :allow_blank => true, :message => "should only contain letters, numbers, or .-_@"
  validates_format_of :email, :with => /^[-a-z0-9_+\.]+\@([-a-z0-9]+\.)+[a-z0-9]{2,4}$/i
  validates_presence_of :password , only: [:create,:update]
  validates_confirmation_of :password 
  validates_length_of :password, :minimum => 4, :allow_blank => true

  # login can be either username or email address
  def self.authenticate(login, pass)
    usuari = self.find(:first, :conditions => [ "lower(username) = ?",login.downcase ]) || find_by_email(login)
    return usuari if usuari && usuari.password_hash == usuari.encrypt_password(pass)
  end

  def encrypt_password(pass)
    BCrypt::Engine.hash_secret(pass, password_salt)
  end

  private

  def prepare_password
    unless password.blank?
      self.password_salt = BCrypt::Engine.generate_salt
      self.password_hash = encrypt_password(password)
    end
  end
end

app/controllers/api_controller.rb
class ApiController < ApplicationController
  skip_before_filter :login_required
  
  def login
    usuari = Usuari.authenticate(params[:user], params[:pass])
    

    json=""
    if usuari
      result = 1
      credits = usuari.saldo
      
      remot = usuari.create_remot
      
      json = "{\"result\":#{result}, \"credits\":#{credits}, \"idSessio\":\"#{remot.hash}\"}"
    else
      result = 0
      
      json = "{\"result\":#{result}}"
    end
    
    render json: json
  end
  
  def carta
    categories = Categoria.includes(:begudes).find(:all)
    render json: categories.to_json(include: { begudes: { include: :extres }}, except: [:created_at, :updated_at])
  end
end

app/controllers/begudes_controller.rb
class BegudesController < ApplicationController
  
  
  # GET /begudes
  # GET /begudes.json
  def index
    @begudes = Beguda.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @begudes }
    end
  end

  # GET /begudes/1
  # GET /begudes/1.json
  def show
    @beguda = Beguda.includes(:extres).find(params[:id])
    @llistaExtres = llistarNomExtres(@beguda)
    
    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @beguda }
    end
  end

  # GET /begudes/new
  # GET /begudes/new.json
  def new
    @beguda = Beguda.new
    @extres = Extra.find(:all)
    @categories = Categoria.all

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @beguda }
    end
  end

  # GET /begudes/1/edit
  def edit
    @beguda = Beguda.find(params[:id])
    @extres = Extra.find(:all)
    @categories = Categoria.all

    @llistaExtres = llistarExtres(@beguda)
  end

  # POST /begudes
  # POST /begudes.json
  def create
    @beguda = Beguda.new(params[:beguda])
    @beguda.afegirExtres(params[:extres])

    respond_to do |format|
      if @beguda.save
        format.html { redirect_to @beguda, notice: 'Beguda was successfully created.' }
        format.json { render json: @beguda, status: :created, location: @beguda }
      else
        format.html { render action: "new" }
        format.json { render json: @beguda.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /begudes/1
  # PUT /begudes/1.json
  def update
    @beguda = Beguda.find(params[:id])
    @beguda.afegirExtres(params[:extres])

    respond_to do |format|
      if @beguda.update_attributes(params[:beguda])
        format.html { redirect_to @beguda, notice: 'Beguda was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render action: "edit" }
        format.json { render json: @beguda.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /begudes/1
  # DELETE /begudes/1.json
  def destroy
    @beguda = Beguda.find(params[:id])
    @beguda.destroy

    respond_to do |format|
      format.html { redirect_to begudes_url }
      format.json { head :ok }
    end
  end
  
  private
  
  def llistarExtres(beguda)
    llistaExtres = [] 
  	@beguda.extres.each {|extra| llistaExtres << extra.id}
  	return llistaExtres
  end
    
  def llistarNomExtres(beguda)
    llistaExtres = [] 
  	@beguda.extres.each {|extra| llistaExtres << extra.nom}
  	return llistaExtres
  end
  
end

app/helpers/api_helper.rb
module ApiHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/begudes_helper.rb
module BegudesHelper
end

app/helpers/botigues_helper.rb
module BotiguesHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/comandes_helper.rb
module ComandesHelper
end

app/helpers/extres_helper.rb
module ExtresHelper
end

app/helpers/layout_helper.rb
# These helper methods can be called in your template to set variables to be used in the layout
# This module should be included in all views globally,
# to do so you may need to add this line to your ApplicationController
#   helper :layout
module LayoutHelper
  def title(page_title, show_title = true)
    content_for(:title) { h(page_title.to_s) }
    @show_title = show_title
  end

  def show_title?
    @show_title
  end

  def stylesheet(*args)
    content_for(:head) { stylesheet_link_tag(*args) }
  end

  def javascript(*args)
    content_for(:head) { javascript_include_tag(*args) }
  end
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/topings_helper.rb
module TopingsHelper
end

app/helpers/usuaris_helper.rb
module UsuarisHelper
end

app/views/begudes/_form.html.erb
<%= form_for(@beguda) do |f| %>
	<% if @beguda.errors.any? %>
	  <div id="error_explanation">
	    <h2><%= pluralize(@beguda.errors.count, "error") %> prohibited this beguda from being saved:</h2>

	    <ul>
	    <% @beguda.errors.full_messages.each do |msg| %>
	      <li><%= msg %></li>
	    <% end %>
	    </ul>
	  </div>
	<% end %>

	<div class="field">
	  <%= f.label :nom %><br />
	  <%= f.text_field :nom %>
	</div>
	<div class="field">
	  <%= f.label :preuTall %><br />
	  <%= f.text_field :preuTall %>
	</div>
	<div class="field">
	  <%= f.label :preuGrande %><br />
	  <%= f.text_field :preuGrande %>
	</div>
	<div class="field">
	  <%= f.label :preuVenti %><br />
	  <%= f.text_field :preuVenti %>
	</div>

  <% if @categories %>
    <div class="field">
      <%= f.label :categoria %><br />
      <%= f.collection_select :categoria_id, @categories, :id, :nom %>
    </div>
  <% end %>
	<% 
	if @extres
		@extres.each do |extra| %>
			<div>
				<% checked = @llistaExtres && @llistaExtres.include?(extra.id) %>
				<%= f.label extra.nom %>
				<%= check_box_tag "extres[]", extra.id.to_s, checked %>
			</div>
	<% 	end
 	else %>
		No extras available
	<% end %>

	<div class="actions">
	  <%= f.submit %>
	</div>
<% end %>

app/views/begudes/edit.html.erb
<h1>Editing beguda</h1>

<%= render 'form' %>

<%= link_to 'Show', @beguda %> |
<%= link_to 'Back', begudes_path %>

app/views/begudes/index.html.erb
<h1>Listing begudes</h1>

<table>
  <tr>
	<th>Nom</th>	
    <th>Preutall</th>
    <th>Preugrande</th>
    <th>Preuventi</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @begudes.each do |beguda| %>
  <tr>
	<td><%= beguda.nom %></td>
    <td><%= beguda.preuTall %></td>
    <td><%= beguda.preuGrande %></td>
    <td><%= beguda.preuVenti %></td>
    <td><%= link_to 'Show', beguda %></td>
    <td><%= link_to 'Edit', edit_beguda_path(beguda) %></td>
    <td><%= link_to 'Destroy', beguda, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Beguda', new_beguda_path %>

app/views/begudes/new.html.erb
<h1>New beguda</h1>

<%= render 'form' %>

<%= link_to 'Back', begudes_path %>

app/views/begudes/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Nom:</b>
  <%= @beguda.nom %>
</p>

<p>
  <b>Preutall:</b>
  <%= @beguda.preuTall %>
</p>

<p>
  <b>Preugrande:</b>
  <%= @beguda.preuGrande %>
</p>

<p>
  <b>Preuventi:</b>
  <%= @beguda.preuVenti %>
</p>

<p>
	<b>Extres:</b> 
	<%= @llistaExtres.to_sentence %>
</p>

<%= link_to 'Edit', edit_beguda_path(@beguda) %> |
<%= link_to 'Back', begudes_path %>